<script lang="ts">
import { getHighlighter, langFromPath } from "./highlight.ts";
import { type ScrollGroup, syncScroll } from "./syncScroll.ts";
import { theme } from "./theme.svelte.ts";

let {
  code,
  path = "",
  lang = "",
  numbered = false,
  startLine = 1,
  scrollGroup,
}: {
  code: string;
  path?: string;
  lang?: string;
  numbered?: boolean;
  startLine?: number;
  scrollGroup?: ScrollGroup;
} = $props();

let html = $state("");

$effect(() => {
  const src = code;
  const wanted = lang || langFromPath(path);
  const themeName = theme.current; // re-highlight when the theme changes
  let cancelled = false;
  void (async () => {
    try {
      const hl = await getHighlighter();
      const useLang = hl.getLoadedLanguages().includes(wanted) ? wanted : "text";
      const useTheme = hl.getLoadedThemes().includes(themeName) ? themeName : "one-dark-pro";
      const out = hl.codeToHtml(src, { lang: useLang, theme: useTheme });
      if (!cancelled) html = out;
    } catch {
      if (!cancelled) html = "";
    }
  })();
  return () => {
    cancelled = true;
  };
});
</script>

{#if html}
  <!-- Shiki output is generated by us from the agent's code; safe to render. -->
  <div class="code" class:numbered style="--start-line: {startLine - 1}" use:syncScroll={scrollGroup}>{@html html}</div>
{:else}
  <pre class="code raw">{code}</pre>
{/if}

<style>
  .code {
    overflow: auto;
    font-size: var(--code-font-size);
    line-height: 1.5;
  }
  /* Let the container's background (plain or diff tint) show; shiki bakes its
     own bg onto pre, so neutralize it. */
  .code :global(pre.shiki) {
    margin: 0;
    padding: 8px 10px;
    background: transparent !important;
    white-space: pre;
    font-family: var(--code-font);
  }
  /* Line numbers via a CSS counter on Shiki's per-line spans. */
  .code.numbered :global(code) {
    counter-reset: line var(--start-line, 0);
  }
  .code.numbered :global(.line)::before {
    counter-increment: line;
    content: counter(line);
    display: inline-block;
    width: 2.5em;
    margin-right: 1em;
    text-align: right;
    color: var(--muted);
    opacity: 0.6;
    user-select: none;
  }
  .raw {
    margin: 0;
    padding: 8px 10px;
    white-space: pre;
    color: var(--fg);
    font-family: var(--code-font);
  }
</style>
