<script lang="ts">
import { getHighlighter, langFromPath } from "./highlight.ts";
import { theme } from "./theme.svelte.ts";

let { code, path = "", lang = "" }: { code: string; path?: string; lang?: string } = $props();

let html = $state("");

$effect(() => {
  const src = code;
  const wanted = lang || langFromPath(path);
  const themeName = theme.current; // re-highlight when the theme changes
  let cancelled = false;
  void (async () => {
    try {
      const hl = await getHighlighter();
      const useLang = hl.getLoadedLanguages().includes(wanted) ? wanted : "text";
      const useTheme = hl.getLoadedThemes().includes(themeName) ? themeName : "one-dark-pro";
      const out = hl.codeToHtml(src, { lang: useLang, theme: useTheme });
      if (!cancelled) html = out;
    } catch {
      if (!cancelled) html = "";
    }
  })();
  return () => {
    cancelled = true;
  };
});
</script>

{#if html}
  <!-- Shiki output is generated by us from the agent's code; safe to render. -->
  <div class="code">{@html html}</div>
{:else}
  <pre class="code raw">{code}</pre>
{/if}

<style>
  .code {
    overflow: auto;
    font-size: 12px;
    line-height: 1.5;
  }
  /* Let the container's background (plain or diff tint) show; shiki bakes its
     own bg onto pre, so neutralize it. */
  .code :global(pre.shiki) {
    margin: 0;
    padding: 8px 10px;
    background: transparent !important;
    white-space: pre;
  }
  .raw {
    margin: 0;
    padding: 8px 10px;
    white-space: pre;
    color: var(--fg);
  }
</style>
